config/routes.rb
Maplight::Application.routes.draw do

  match '/search/results' => 'search#results', :as => :results
  match '/search' => 'search#index'
  root :to => 'search#index'

end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
  end

  def results
    donor = params[:donor]
    recipient = params[:recipient]

    if donor != '' and recipient != ''
      @donor = donor
      @recipient = recipient
      @contributions = Contribution.find(:all, :conditions => ["donor LIKE ? and recipient LIKE ?" , '%'+donor+'%', '%'+recipient+'%'])
    elsif donor != '' 
      # only donor filled in 
      @donor = donor
      @contributions = Contribution.find(:all, :conditions => ['donor LIKE ?', '%'+donor+'%'])
    elsif recipient != ''
      # only recipient filled in 
      @recipient = recipient
      @contributions = Contribution.find(:all, :conditions => ['recipient LIKE ?', '%'+recipient+'%'])
    else
      # nothing filled in, show all contributions
      @contributions = Contribution.all
    end

    if @contributions.count == 0
      flash[:notice] = 'Sorry, no entries matched. Please try again.'
      redirect_to search_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maplight</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search/all.html.haml
%h1 Search#index
%p Find me in app/views/search/all.html.haml

%table#contributions
	%thead
		%tr
			%th Date
			%th Contributor
			%th Amount
			%th City 
			%th State
			%th Recipient
	%tbody
		- @contributions.each do |contribution|
			%tr
				%td= contribution.date 
				%td= contribution.contributor
				%td= contribution.amount
				%td= contribution.city
				%td= contribution.state
				%td= contribution.recipient

app/views/search/index.html.haml
%h1 Search

%p= flash[:notice]

= form_tag results_path :method => :get do

  = label_tag 'donor', 'Donor' 
  = text_field_tag 'donor' 

  = label_tag 'recipient', 'Recipient'
  = text_field_tag 'recipient' 

  = submit_tag 'Search'

= link_to 'See all contributions', results_path(:donor => '', :recipient => '')

app/views/search/results.html.haml
%h1 Search

- if defined? @donor and defined? @recipient
  %p= ('Contributions from ' + @donor + ' to ' + @recipient)
- elsif defined? @donor
  %p= ('Contributions from ' + @donor)
- elsif defined? @recipient
  %p= ('Contributions to ' + @recipient) 

%table#contributions
  %thead
    %tr
      %th Contributor
      %th Recipient
      %th Amount 
      %th City
      %th State
      %tbody
      - @contributions.each do |contribution|
        %tr
          %td= contribution.donor 
          %td= contribution.recipient
          %td= contribution.amount
          %td= contribution.city
          %td= contribution.state

=link_to 'Go back to Search', {:controller => :search, :action => :index}